http {
    server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.jpg$ {
            return 403;
        }
    }

    server {
        listen 8888;
        location / {
            proxy_pass http://host.docker.internal:8080;
        }
    }
}

events {}