http {
    server {
        listen 80;
        listen 443 ssl;

        //ssl_certificate /etc/nginx/certs/cert.pem;
        //ssl_certificate_key /etc/nginx/certs/key.pem;

        location / {
            return 301 https://$host$request_uri;
        }
    }
}

events {}